project = "apache.org/serf"
why     = "This recipe pins openssl to a 1.x line. Our registry holds no 1.x bottle — every one of the 48 is 3.x or 4.x — so the recipe dies in the resolver before a compiler runs: `no version of openssl.org satisfies \"^1.1\"`. openssl 1.1.1 has been end-of-life since September 2023, so pinning it is not an alternative. Generated by ./openssl3; delete this when upstream retargets the pin."

edits = [
  {
    path = "build.script"
    set = [
      {
        "prop" = <<EOT
s/env = Environment(variables=opts,/env = Environment(ENV = os.environ, variables=opts,/
EOT
        "run" = "sed -i -f $PROP SConstruct"
      },
      "scons \"LINKFLAGS=$LDFLAGS\" $ARGS",
      "scons install",
    ]
    expect = [
      {
        "prop" = <<EOT
s/env = Environment(variables=opts,/env = Environment(ENV = os.environ, variables=opts,/
EOT
        "run" = "sed -i -f $PROP SConstruct"
      },
      "scons $ARGS",
      "scons install",
    ]
  },
  {
    path = "dependencies[\"openssl.org\"]"
    set = "^3"
  },
]
