project = "crates.io/jwt-cli"
why     = "`cargo install` without --locked ignores the Cargo.lock the release ships and re-resolves every dependency to the newest semver-compatible crate. The recipe does not change, the source does not change, and the build rots anyway on someone else's release schedule. Generated by ./cargolocked; delete this when upstream adds --locked."

edits = [
  {
    path = "build.script"
    from = "install --path"
    to   = "install --locked --path"
  },
]
