project = "crates.io/zellij"
why     = "Two corrections, and the second was impossible while these were unified diffs: the openssl patch carried the cargo install line as CONTEXT, so rewriting it stopped the openssl patch applying and the build died naming openssl. See go-pkgx/packages#271.\n\nThis recipe pins openssl to a 1.x line. Our registry holds no 1.x bottle — every one of the 48 is 3.x or 4.x — so the recipe dies in the resolver before a compiler runs: `no version of openssl.org satisfies \"^1.1\"`. openssl 1.1.1 has been end-of-life since September 2023, so pinning it is not an alternative. Generated by ./openssl3; delete this when upstream retargets the pin."

edits = [
  {
    path = "build.dependencies[\"openssl.org\"]"
    set = "^3"
  },
  {
    why  = "`cargo install` without --locked ignores the Cargo.lock the release ships and re-resolves every dependency to the newest semver-compatible crate; the build then rots on somebody else's release schedule. Generated by ./cargolocked; delete this when upstream adds --locked."
    path = "build.script"
    from = "install --path"
    to   = "install --locked --path"
  },
]
