project = "developers.yubico.com/libfido2"
why     = "This recipe pins openssl to a 1.x line. Our registry holds no 1.x bottle — every one of the 48 is 3.x or 4.x — so the recipe dies in the resolver before a compiler runs: `no version of openssl.org satisfies \"^1.1\"`. openssl 1.1.1 has been end-of-life since September 2023, so pinning it is not an alternative. Generated by ./openssl3; delete this when upstream retargets the pin."

edits = [
  {
    path = "build.env.ARGS"
    append = [
      "-DBUILD_TESTS=OFF",
      "-DBUILD_EXAMPLES=OFF",
    ]
  },
  {
    path = "build.env.CFLAGS"
    set = "$CFLAGS -include err.h"
  },
  {
    path = "dependencies[\"openssl.org\"]"
    set = "^3"
  },
]
