project = "facebook.com/fbthrift"
why     = "This recipe pins openssl to a 1.x line. Our registry holds no 1.x bottle — every one of the 48 is 3.x or 4.x — so the recipe dies in the resolver before a compiler runs: `no version of openssl.org satisfies \"^1.1\"`. openssl 1.1.1 has been end-of-life since September 2023, so pinning it is not an alternative. Generated by ./openssl3; delete this when upstream retargets the pin."

edits = [
  {
    path = "build.dependencies.darwin"
    set = {
      "llvm.org" = "*"
    }
  },
  {
    path = "build.env.darwin.CMAKE_ARGS"
    remove = true
  },
  {
    path = "build.script"
    set = [
      {
        "if" = "linux/aarch64"
        "run" = "sed -i 's/^static_assert(is_supported_integral_type<char>);/\\/\\/&/' object.h"
        "working-directory" = "thrift/compiler/whisker"
      },
      {
        "if" = "darwin"
        "run" = <<EOT
if test -f FindFmt.cmake; then
  sed -i 's/add_library(fmt::fmt UNKNOWN IMPORTED)/#&/' FindFmt.cmake
fi
EOT
        "working-directory" = "thrift/cmake"
      },
      {
        "if" = "darwin"
        "run" = "sed -i 's/switch (token_.kind)/switch (tok(token_.kind))/g' parser_core.h"
        "working-directory" = "thrift/compiler/parse"
      },
      {
        "prop" = <<EOT
/AsyncProcessor\.h/a\
#include <fmt/ranges.h>
EOT
        "run" = "sed -i -f $PROP RoundRobinRequestPile.h"
        "working-directory" = "thrift/lib/cpp2/server"
      },
      {
        "if" = ">=2026.6.8"
        "prop" = <<EOT
/#pragma once/a\
#include <cstring>
EOT
        "run" = [
          "for f in thrift/lib/cpp2/frozen/FixedSizeStringHash.h thrift/lib/cpp2/protocol/JSONProtocolCommon-inl.h; do",
          "if grep -q '#include <cstring>' \"$f\"; then continue; fi",
          "sed -i -f $PROP \"$f\"",
          "done",
          "if ! grep -q '#include <cstring>' thrift/compiler/generate/t_concat_generator.cc; then",
          <<EOT
sed -i -e '/#include <cinttypes>/a\
#include <cstring>' thrift/compiler/generate/t_concat_generator.cc
EOT
          ,
          "fi",
          "for f in $(grep -R -l 'fmt::format' thrift); do",
          "if grep -q '#include <fmt/format\\.h>' \"$f\"; then continue; fi",
          <<EOT
sed -i -e '/#include <fmt\/core\.h>/a\
#include <fmt/format.h>' "$f"
EOT
          ,
          "done",
        ]
      },
      {
        "if" = "linux"
        "run" = "export PATH={{deps.gnu.org/binutils.prefix}}/bin:$PATH"
      },
      {
        "if" = "darwin"
        "run" = "cmake -S . $CMAKE_ARGS \"-DCMAKE_SHARED_LINKER_FLAGS=$LDFLAGS -Wl,-undefined,dynamic_lookup,-dead_strip_dylibs\" \"-DCMAKE_EXE_LINKER_FLAGS=$LDFLAGS -Wl,-dead_strip_dylibs\""
      },
      {
        "if" = "linux"
        "run" = "cmake -S . $CMAKE_ARGS"
      },
      "cmake --build .",
      "cmake --install .",
      {
        "run" = "sed -i -E -e \"s:{{pkgx.prefix}}:\\$\\{_IMPORT_PREFIX\\}/../../..:g\" -e '/^  INTERFACE_INCLUDE_DIRECTORIES/ s|/v([0-9]+)(\\.[0-9]+)*[a-z]?/include|/v\\1/include|g' -e '/^  INTERFACE_LINK_LIBRARIES/ s|/v([0-9]+)(\\.[0-9]+)*[a-z]?/lib|/v\\1/lib|g' FBThriftTargets.cmake"
        "working-directory" = "$${{prefix}}/lib/cmake/fbthrift"
      },
    ]
    expect = [
      {
        "if" = "linux/aarch64"
        "run" = "sed -i 's/^static_assert(is_supported_integral_type<char>);/\\/\\/&/' object.h"
        "working-directory" = "thrift/compiler/whisker"
      },
      {
        "if" = "darwin"
        "run" = <<EOT
if test -f FindFmt.cmake; then
  sed -i 's/add_library(fmt::fmt UNKNOWN IMPORTED)/#&/' FindFmt.cmake
fi
EOT
        "working-directory" = "thrift/cmake"
      },
      {
        "if" = "darwin"
        "run" = "sed -i 's/switch (token_.kind)/switch (tok(token_.kind))/g' parser_core.h"
        "working-directory" = "thrift/compiler/parse"
      },
      {
        "prop" = <<EOT
/AsyncProcessor\.h/a\
#include <fmt/ranges.h>
EOT
        "run" = "sed -i -f $PROP RoundRobinRequestPile.h"
        "working-directory" = "thrift/lib/cpp2/server"
      },
      {
        "if" = ">=2026.6.8"
        "prop" = <<EOT
/#pragma once/a\
#include <cstring>
EOT
        "run" = [
          "for f in thrift/lib/cpp2/frozen/FixedSizeStringHash.h thrift/lib/cpp2/protocol/JSONProtocolCommon-inl.h; do",
          "if grep -q '#include <cstring>' \"$f\"; then continue; fi",
          "sed -i -f $PROP \"$f\"",
          "done",
          "if ! grep -q '#include <cstring>' thrift/compiler/generate/t_concat_generator.cc; then",
          <<EOT
sed -i -e '/#include <cinttypes>/a\
#include <cstring>' thrift/compiler/generate/t_concat_generator.cc
EOT
          ,
          "fi",
          "for f in $(grep -R -l 'fmt::format' thrift); do",
          "if grep -q '#include <fmt/format\\.h>' \"$f\"; then continue; fi",
          <<EOT
sed -i -e '/#include <fmt\/core\.h>/a\
#include <fmt/format.h>' "$f"
EOT
          ,
          "done",
        ]
      },
      {
        "if" = "linux"
        "run" = "export PATH={{deps.gnu.org/binutils.prefix}}/bin:$PATH"
      },
      "cmake -S . $CMAKE_ARGS",
      "cmake --build .",
      "cmake --install .",
      {
        "run" = "sed -i -E -e \"s:{{pkgx.prefix}}:\\$\\{_IMPORT_PREFIX\\}/../../..:g\" -e '/^  INTERFACE_INCLUDE_DIRECTORIES/ s|/v([0-9]+)(\\.[0-9]+)*[a-z]?/include|/v\\1/include|g' -e '/^  INTERFACE_LINK_LIBRARIES/ s|/v([0-9]+)(\\.[0-9]+)*[a-z]?/lib|/v\\1/lib|g' FBThriftTargets.cmake"
        "working-directory" = "$${{prefix}}/lib/cmake/fbthrift"
      },
    ]
  },
  {
    path = "dependencies[\"openssl.org\"]"
    set = "^3"
  },
]
