project = "grpc.io"
why     = "This recipe pins openssl to a 1.x line. Our registry holds no 1.x bottle — every one of the 48 is 3.x or 4.x — so the recipe dies in the resolver before a compiler runs: `no version of openssl.org satisfies \"^1.1\"`. openssl 1.1.1 has been end-of-life since September 2023, so pinning it is not an alternative. Generated by ./openssl3; delete this when upstream retargets the pin."

edits = [
  {
    path = "build.env.COMMON_ARGS"
    set = [
      "-DCMAKE_BUILD_TYPE=Release",
      "-DCMAKE_INSTALL_PREFIX=\"{{prefix}}\"",
      "-DCMAKE_INSTALL_RPATH=\"{{prefix}};@loader_path/../../..;@loader_path/../../../..;@loader_path/../../../../..;@loader_path/../../../../../..;@loader_path/../../../../../../..\"",
      "-DBUILD_SHARED_LIBS=ON",
    ]
    expect = [
      "-DCMAKE_BUILD_TYPE=Release",
      "-DCMAKE_INSTALL_PREFIX=\"{{prefix}}\"",
      "-DCMAKE_INSTALL_RPATH={{prefix}}",
      "-DBUILD_SHARED_LIBS=ON",
    ]
  },
  {
    path = "build.script"
    from = "lib/libgrpc++_test_config.dylib; do\n  if test -f $f && ! otool -l $f | grep @loader_path/../lib; then\n    install_name_tool -add_rpath @loader_path/../lib $f\n  fi"
    to   = "lib/libgrpc++_test_config*.dylib; do\n  test -f $f || continue\n  for rp in @loader_path/../lib @loader_path/../../..; do\n    # Compare the PATH FIELD, not the end of the line. otool prints\n    #     path @loader_path/../../.. (offset 12)\n    # so an anchored match never fired, install_name_tool was called\n    # for an rpath the file already had, and it exits non-zero:\n    #     option \"-add_rpath @loader_path/../../..\" would duplicate\n    #     path, file already has LC_RPATH for: @loader_path/../../..\n    # which failed the whole build. grpc_cli already carries that one.\n    otool -l $f | awk '$1==\"path\"{print $2}' | grep -qxF \"$rp\" ||\n      install_name_tool -add_rpath $rp $f\n  done"
  },
  {
    path = "dependencies[\"openssl.org\"]"
    set = "^3"
  },
]
