project = "tcl-lang.org"
why     = "This recipe pins openssl to a 1.x line. Our registry holds no 1.x bottle — every one of the 48 is 3.x or 4.x — so the recipe dies in the resolver before a compiler runs: `no version of openssl.org satisfies \"^1.1\"`. openssl 1.1.1 has been end-of-life since September 2023, so pinning it is not an alternative. Generated by ./openssl3; delete this when upstream retargets the pin."

edits = [
  {
    path = "build.script"
    set = [
      {
        "run" = "./configure $ARGS"
        "working-directory" = "unix"
      },
      {
        "if" = ">=9.0.4"
        "run" = [
          "make --jobs {{hw.concurrency}} binaries",
          "mkdir -p {{prefix}}/lib",
          # Derived, not typed. tcl released 9.1.0 between two sovereign
          # generations four hours apart -- on the SAME pantry commit
          # 2df061bd, because `versions:` asks GitHub for tags at RESOLVE
          # time -- and this line stopped finding the library the build had
          # just made:
          #
          #   07:44Z  ✅ OK          tcl-lang.org 9.0.4
          #   11:14Z  ❌ BUILD FAIL  cp: cannot stat 'libtcl9.0.*'
          #
          # Three lines down the same number is already written as
          # {{version.marketing}}. For 9.0.4 this renders byte-for-byte what
          # was there, so the version that worked is untouched.
          #
          # `expect` below keeps the literal, because that is what UPSTREAM
          # still says and the premise has to describe upstream.
          "cp libtcl{{version.marketing}}.* {{prefix}}/lib/",
          "export LD_LIBRARY_PATH=\"{{prefix}}/lib:$LD_LIBRARY_PATH\"",
        ]
        "working-directory" = "unix"
      },
      {
        "run" = [
          "make --jobs {{hw.concurrency}}",
          "make --jobs {{hw.concurrency}} install",
          "make --jobs {{hw.concurrency}} install-private-headers",
        ]
        "working-directory" = "unix"
      },
      {
        "run" = "if test ! -f tclsh; then ln -s tclsh{{version.marketing}} tclsh; fi"
        "working-directory" = "{{prefix}}/bin"
      },
      {
        "if" = "<8.6.14"
        "run" = [
          "curl -L \"$patch_1\" | patch -p0",
          "curl -L \"$patch_2\" | patch -p0",
        ]
        "working-directory" = "tk"
      },
      {
        "run" = [
          "curl -L \"$res_tk\" | tar -xz --strip-components=1",
          "cd unix",
          "./configure $ARGS --without-x --with-tcl={{prefix}}/lib",
          "make --jobs {{hw.concurrency}}",
          "make --jobs {{hw.concurrency}} install",
          "make --jobs {{hw.concurrency}} install-private-headers",
        ]
        "working-directory" = "tk"
      },
      {
        "run" = "if test ! -f wish; then ln -s wish{{version.marketing}} wish; fi"
        "working-directory" = "{{prefix}}/bin"
      },
      {
        "run" = [
          "curl -L \"$res_critcl\" | tar -xz --strip-components=1",
          "sed -i \"s|package require Tcl 8.6.9$|package require Tcl {{version.major}}|g\" build.tcl",
          "tclsh build.tcl install",
        ]
        "working-directory" = "critcl"
      },
      {
        "run" = [
          "curl -L \"$res_tcllib\" | tar -xJ --strip-components=1",
          "./configure --prefix={{prefix}} --mandir={{prefix}}/share/man",
          "sed -i \"s|package require Tcl 8.2|package require Tcl {{version.major}}|g\" installer.tcl",
          "make --jobs {{hw.concurrency}} install",
          "make --jobs {{hw.concurrency}} critcl",
          "cp -r modules/tcllibc {{prefix}}/lib/",
        ]
        "working-directory" = "tcllib"
      },
      {
        "run" = [
          "curl -L \"$res_tcltls\" | tar -xz --strip-components=1",
          "sed -i '/SSL_SESSION_get0_ticket_appdata/s/&ticket/(void **)\\&ticket/' generic/tls.c",
          "./configure $TLS_ARGS",
          "make --jobs {{hw.concurrency}}",
          "make --jobs {{hw.concurrency}} install",
        ]
        "working-directory" = "tcltls"
      },
      {
        "run" = [
          "curl -L \"$res_itk4\" | tar -xz --strip-components=1",
          "itcl_dir=$(ls -d {{prefix}}/lib/itcl* | tail -n 1)",
          "./configure $ITK4_ARGS --with-itcl=$itcl_dir",
          "make --jobs {{hw.concurrency}}",
          "cp -a ../tcltls/tclconfig .",
          "make install",
        ]
        "working-directory" = "itk4"
      },
      "rm {{prefix}}/bin/sqlite3_analyzer",
      {
        "prop" = <<EOT
s|='\(.*\){{prefix}}\(.*\)'|="\1$(cd $(dirname $0) \&\& pwd)/..\2"|g
s|="\(.*\){{prefix}}\(.*\)"|="\1$(cd $(dirname $0) \&\& pwd)/..\2"|g
EOT
        "run" = "sed -i -f $PROP *.sh"
        "working-directory" = "{{prefix}}/lib"
      },
      {
        "prop" = <<EOT
s|='\(.*\){{prefix}}\(.*\)'|="\1$(cd $(dirname $0) \&\& pwd)/../..\2"|g
s|="\(.*\){{prefix}}\(.*\)"|="\1$(cd $(dirname $0) \&\& pwd)/../..\2"|g
EOT
        "run" = "sed -i -f $PROP */*.sh"
        "working-directory" = "{{prefix}}/lib"
      },
    ]
    expect = [
      {
        "run" = "./configure $ARGS"
        "working-directory" = "unix"
      },
      {
        "if" = ">=9.0.4"
        "run" = [
          "make --jobs {{hw.concurrency}} binaries",
          "mkdir -p {{prefix}}/lib",
          "cp libtcl9.0.* {{prefix}}/lib/",
          "export LD_LIBRARY_PATH=\"{{prefix}}/lib:$LD_LIBRARY_PATH\"",
        ]
        "working-directory" = "unix"
      },
      {
        "run" = [
          "make --jobs {{hw.concurrency}}",
          "make --jobs {{hw.concurrency}} install",
          "make --jobs {{hw.concurrency}} install-private-headers",
        ]
        "working-directory" = "unix"
      },
      {
        "run" = "if test ! -f tclsh; then ln -s tclsh{{version.marketing}} tclsh; fi"
        "working-directory" = "{{prefix}}/bin"
      },
      {
        "if" = "<8.6.14"
        "run" = [
          "curl -L \"$patch_1\" | patch -p0",
          "curl -L \"$patch_2\" | patch -p0",
        ]
        "working-directory" = "tk"
      },
      {
        "run" = [
          "curl -L \"$res_tk\" | tar -xz --strip-components=1",
          "cd unix",
          "./configure $ARGS --without-x --with-tcl={{prefix}}/lib",
          "make --jobs {{hw.concurrency}}",
          "make --jobs {{hw.concurrency}} install",
          "make --jobs {{hw.concurrency}} install-private-headers",
        ]
        "working-directory" = "tk"
      },
      {
        "run" = "if test ! -f wish; then ln -s wish{{version.marketing}} wish; fi"
        "working-directory" = "{{prefix}}/bin"
      },
      {
        "run" = [
          "curl -L \"$res_critcl\" | tar -xz --strip-components=1",
          "sed -i \"s|package require Tcl 8.6.9$|package require Tcl {{version.major}}|g\" build.tcl",
          "tclsh build.tcl install",
        ]
        "working-directory" = "critcl"
      },
      {
        "run" = [
          "curl -L \"$res_tcllib\" | tar -xJ --strip-components=1",
          "./configure --prefix={{prefix}} --mandir={{prefix}}/share/man",
          "sed -i \"s|package require Tcl 8.2|package require Tcl {{version.major}}|g\" installer.tcl",
          "make --jobs {{hw.concurrency}} install",
          "make --jobs {{hw.concurrency}} critcl",
          "cp -r modules/tcllibc {{prefix}}/lib/",
        ]
        "working-directory" = "tcllib"
      },
      {
        "run" = [
          "curl -L \"$res_tcltls\" | tar -xz --strip-components=1",
          "sed -i '/SSL_SESSION_get0_ticket_appdata/s/&ticket/(void **)\\&ticket/' generic/tls.c",
          "./configure $TLS_ARGS",
          "make --jobs {{hw.concurrency}}",
          "make --jobs {{hw.concurrency}} install",
        ]
        "working-directory" = "tcltls"
      },
      {
        "run" = [
          "curl -L \"$res_itk4\" | tar -xz --strip-components=1",
          "itcl_dir=$(ls -d {{prefix}}/lib/itcl* | tail -n 1)",
          "./configure $ITK4_ARGS --with-itcl=$itcl_dir",
          "make --jobs {{hw.concurrency}}",
          "cp -a ../tcltls/tclconfig .",
          "make install",
        ]
        "working-directory" = "itk4"
      },
      "rm {{prefix}}/bin/sqlite3_analyzer",
      {
        "prop" = <<EOT
s|='\(.*\){{prefix}}\(.*\)'|="\1$(cd $(dirname $0) \&\& pwd)/..\2"|g
s|="\(.*\){{prefix}}\(.*\)"|="\1$(cd $(dirname $0) \&\& pwd)/..\2"|g
EOT
        "run" = "sed -i -f $PROP *.sh"
        "working-directory" = "{{prefix}}/lib"
      },
      {
        "prop" = <<EOT
s|='\(.*\){{prefix}}\(.*\)'|="\1$(cd $(dirname $0) \&\& pwd)/../..\2"|g
s|="\(.*\){{prefix}}\(.*\)"|="\1$(cd $(dirname $0) \&\& pwd)/../..\2"|g
EOT
        "run" = "sed -i -f $PROP */*.sh"
        "working-directory" = "{{prefix}}/lib"
      },
      {
        "if" = "darwin"
        "run" = [
          "for f in $(find bin lib -type f); do",
          "file \"$f\" | grep -q Mach-O || continue",
          "up=\"$(dirname \"$f\" | sed 's:[^/][^/]*:..:g')\"",
          "id=$(otool -D \"$f\" | sed -n 2p)",
          "case \"$id\" in {{prefix}}/*) install_name_tool -id \"@rpath/$${id##*/}\" \"$f\";; esac",
          "for dep in $(otool -L \"$f\" | awk 'NR>1{print $1}' | grep -F \"{{prefix}}/\"); do",
          "install_name_tool -change \"$dep\" \"@loader_path/$up/$${dep#{{prefix}}/}\" \"$f\"",
          "done",
          "install_name_tool -add_rpath \"@loader_path/$up/../..\" \"$f\"",
          "if otool -l \"$f\" | grep -qF \"{{pkgx.prefix}} (offset\"; then install_name_tool -delete_rpath {{pkgx.prefix}} \"$f\"; fi",
          "codesign --remove-signature \"$f\"",
          "codesign -s - --force \"$f\"",
          "done",
        ]
        "working-directory" = "$${{prefix}}"
      },
    ]
  },
  {
    path = "build.skip"
    remove = true
  },
  {
    path = "dependencies[\"openssl.org\"]"
    set = "^3"
  },
  {
    path = "versions.match"
    set = "/Tcl\\/\\d+\\.\\d+\\.\\d+\\//"
  },
  {
    path = "versions.strip"
    set = [
      "/^Tcl\\//",
      "/\\/$/",
    ]
    expect = [
      "/^tcl/",
      "/-src\\.tar\\.gz/",
    ]
  },
  {
    path = "versions.url"
    set = "https://sourceforge.net/projects/tcl/files/Tcl/"
  },
]
