project = "zsync.moria.org.uk"
why     = "This recipe pins openssl to a 1.x line. Our registry holds no 1.x bottle — every one of them is 3.x or 4.x — so the recipe dies in the resolver before a compiler runs: no version of openssl.org satisfies ^1.1. openssl 1.1.1 has been end-of-life since September 2023, so pinning it is not a real alternative. This does NOT prove the recipe builds against openssl 3; it makes it RESOLVE, and a recipe using a removed 1.1 API will now fail in the compiler instead. Generated by ./openssl3; delete it when upstream retargets the pin."

edits = [
  {
    path = "dependencies[\"openssl.org\"]"
    set = "^3"
  },
]
