package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/go-pkgx/bk/logical"
	"gopkg.in/yaml.v3"
)

// overrideFor writes the correction as a LOGICAL override: one `set` per place
// the recipe pins openssl, addressed by key.
//
// This replaces fifty lines of hunk arithmetic — counting context, merging
// spans that would overlap, getting `@@ -n,m +n,m @@` right — and every one of
// those lines existed only because a unified diff has to say WHERE. None of it
// said anything about openssl.
//
// It also removes the caveat the tool had to carry: the line-based rewrite
// "touches ONLY the constraint value on a dependency line naming openssl.org,
// and preserves the line's indentation, quoting style and trailing comment.
// Anything it cannot parse that way is left alone and reported." Nothing is
// parsed that way any more. The recipe is read as a document, every path that
// pins openssl is found wherever it sits — runtime, build, under a platform —
// and the value is assigned. Indentation and comments are not touched because
// the file is not touched.
func overrideFor(pantryDir, proj string) ([]byte, error) {
	paths, err := stalePinPaths(pantryDir, proj)
	if err != nil {
		return nil, err
	}
	ops := make([]logical.Op, 0, len(paths))
	for _, p := range paths {
		ops = append(ops, logical.Op{Why: reason, Path: p, Set: want})
	}
	return logical.Emit(&logical.Override{Project: proj, Why: reason, Ops: ops}), nil
}

// stalePinPaths is every place a recipe pins openssl to a 1.x line.
func stalePinPaths(pantryDir, proj string) ([]logical.Path, error) {
	b, err := os.ReadFile(filepath.Join(pantryDir, "projects", filepath.FromSlash(proj), "package.yml"))
	if err != nil {
		return nil, err
	}
	var doc map[string]any
	if err := yaml.Unmarshal(b, &doc); err != nil {
		return nil, err
	}
	paths := stalePins(doc, nil)
	if len(paths) == 0 {
		return nil, fmt.Errorf("no openssl pin")
	}
	sort.Slice(paths, func(i, j int) bool { return paths[i].String() < paths[j].String() })
	return paths, nil
}

// carriesThePins reports whether an override file already sets every one of
// these paths to the constraint we want.
//
// A project can have an override for more than one reason — apache.org/serf
// needs a scons fix as well as this one, apache.org/subversion a gettext pin —
// and a project's operations live in ONE file so they are read and argued
// about together. A generator therefore cannot own such a file: rewriting it
// would throw away somebody's work and their reasons for it.
//
// So it owns the files it writes and CHECKS the ones it shares. That is the
// right posture for a generator on a re-run anyway: the question is not "what
// would I write" but "is what is there still correct".
func carriesThePins(path string, paths []logical.Path) (bool, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	o, err := logical.Parse(src, filepath.Base(path))
	if err != nil {
		return false, err
	}
	for _, p := range paths {
		found := false
		for _, op := range o.Ops {
			if op.Path.String() == p.String() && op.Set == want {
				found = true
				break
			}
		}
		if !found {
			return false, nil
		}
	}
	return true, nil
}

// reason is what the override says about itself. `why` is required, and this
// is the field that lets somebody DELETE the override one day: the condition
// for removing it is written down.
const reason = `This recipe pins openssl to a 1.x line. Our registry holds no 1.x bottle — ` +
	`every one of them is 3.x or 4.x — so the recipe dies in the resolver before a compiler runs: ` +
	`no version of openssl.org satisfies ^1.1. openssl 1.1.1 has been end-of-life since ` +
	`September 2023, so pinning it is not a real alternative. This does NOT prove the recipe ` +
	`builds against openssl 3; it makes it RESOLVE, and a recipe using a removed 1.1 API will now ` +
	`fail in the compiler instead. Generated by ./openssl3; delete it when upstream retargets the pin.`

// stalePins finds every path at which a recipe pins openssl to a 1.x line,
// wherever it sits: runtime dependencies, build dependencies, or either of
// those under a platform key.
//
// A walk rather than a list of the three places it is usually written. The
// places are not ours to enumerate — `dependencies.linux.openssl.org` and
// `build.dependencies.darwin.openssl.org` both occur in the pantry today — and
// a list is a guess that goes quietly out of date.
func stalePins(v any, prefix logical.Path) []logical.Path {
	m, ok := v.(map[string]any)
	if !ok {
		return nil
	}
	var out []logical.Path
	for k, sub := range m {
		p := append(append(logical.Path{}, prefix...), k)
		if k == "openssl.org" {
			if isStale(sub) {
				out = append(out, p)
			}
			continue
		}
		out = append(out, stalePins(sub, p)...)
	}
	return out
}

// isStale reports whether a constraint asks for openssl 1.x.
//
// The value may be a string ("^1.1", "1.1", ">=1.1<2") or a number: YAML reads
// an unquoted 1.1 as a float, and `amp.rs` writes it that way. Reading only
// strings missed it, and the conversion caught the difference —
// `string(^3) became float64(1.1)`.
func isStale(v any) bool {
	var s string
	switch t := v.(type) {
	case string:
		s = t
	case float64, int:
		s = fmt.Sprint(t)
	default:
		return false
	}
	s = strings.TrimLeft(s, "^~>=< ")
	return strings.HasPrefix(s, "1.") || s == "1"
}
