package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/go-pkgx/bk/logical"
	"gopkg.in/yaml.v3"
)

// overrideFor writes the correction as a LOGICAL override.
//
// It replaces the diff machinery this tool was mostly made of — hunk spans,
// three lines of context, merging ranges that touch — and with it a whole
// CLASS of defect that existed only because two diffs can share a line.
//
// crates.io/zellij is the case that showed it. The openssl3 patch carried
//
//	script: cargo install --path .
//
// as CONTEXT; this tool rewrote that line; the openssl3 patch then stopped
// applying, and the build died on
//
//	resolve deps: no version of openssl.org satisfies "^1.1"
//
// which names openssl and has nothing to do with openssl. Guarding against it
// took hunkRangesByFile, overlaps and collides — and still cost two projects,
// excluded because their spans overlapped. Two logical overrides cannot
// interact that way: openssl3 assigns `dependencies["openssl.org"]` and this
// edits `build.script`.
//
// The operations are DERIVED rather than written by hand. The obvious hand
// version — substitute "cargo install " for "cargo install --locked " — is not
// idempotent: the replacement contains the run, so a second pass yields
// `--locked --locked`. That is the defect go-pkgx/bk#229 was written about, and
// building the document we want and asking logical.Derive for the difference
// inherits the rule instead of re-deriving it badly.
func overrideFor(pantryDir, proj string) ([]byte, error) {
	before, err := recipeDoc(pantryDir, proj)
	if err != nil {
		return nil, err
	}
	copied, n := lockedCopy(before)
	if n == 0 {
		return nil, fmt.Errorf("no unlocked cargo install")
	}
	after, _ := copied.(map[string]any)
	// No `len(ops) == 0` guard: lockedCopy reported a change, so the two
	// documents differ, so Derive returns at least one operation. It would
	// have been untestable, which is the tell.
	ops := logical.Derive(before, after, reason)
	return logical.Emit(&logical.Override{Project: proj, Why: reason, Ops: ops}), nil
}

// reason is what the override says about itself, including what would make it
// unnecessary — which is the whole point of the field.
const reason = "`cargo install` without --locked ignores the Cargo.lock the release ships and " +
	"re-resolves every dependency to the newest semver-compatible crate. The recipe does not " +
	"change, the source does not change, and the build rots anyway, on somebody else's release " +
	"schedule: crates.io/pqrs 0.3.2 locks chrono 0.4.38 and cargo picked 0.4.45. " +
	"Generated by ./cargolocked; delete this when upstream adds --locked."

func recipeDoc(pantryDir, proj string) (map[string]any, error) {
	b, err := os.ReadFile(filepath.Join(pantryDir, "projects", filepath.FromSlash(proj), "package.yml"))
	if err != nil {
		return nil, err
	}
	var doc map[string]any
	if err := yaml.Unmarshal(b, &doc); err != nil {
		return nil, err
	}
	return doc, nil
}

// lockedCopy returns the recipe as it should read, and how many install
// commands it changed. It walks the whole document rather than looking in the
// places a cargo recipe usually puts its script: a platform-scoped script is
// found without this tool knowing to look there.
func lockedCopy(v any) (any, int) {
	switch t := v.(type) {
	case map[string]any:
		out := make(map[string]any, len(t))
		n := 0
		for k, e := range t {
			c, m := lockedCopy(e)
			out[k], n = c, n+m
		}
		return out, n
	case []any:
		out := make([]any, len(t))
		n := 0
		for i, e := range t {
			c, m := lockedCopy(e)
			out[i], n = c, n+m
		}
		return out, n
	case string:
		return lockLines(t)
	default:
		return v, 0
	}
}

// lockLines adds --locked to every unlocked `cargo install` in a command,
// line by line. A build script is one string holding many lines, and a recipe
// may install twice with only one of them already locked.
func lockLines(s string) (string, int) {
	lines := strings.Split(s, "\n")
	n := 0
	for i, line := range lines {
		if !rewritable(line) {
			continue
		}
		m := installLine.FindStringSubmatch(line)
		lines[i] = m[1] + " --locked" + m[2]
		n++
	}
	return strings.Join(lines, "\n"), n
}

// carriesTheFlag reports whether an override already adds --locked.
//
// A project can need an override for more than one reason, and they live in
// one file. The generator therefore owns the files it writes and CHECKS the
// ones it shares — which is the right question on a re-run anyway: not "what
// would I write" but "is what is there still correct".
func carriesTheFlag(path string) (bool, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	o, err := logical.Parse(src, filepath.Base(path))
	if err != nil {
		return false, err
	}
	for _, op := range o.Ops {
		if op.Substitute && strings.Contains(op.To, "--locked") && !strings.Contains(op.From, "--locked") {
			return true, nil
		}
	}
	return false, nil
}
